# -*- coding: utf-8 -*-
"""SFCN_modified_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxPW3ORSxmzVylhs9wURsL9EVu1SmDhj

# SFCN
github 코드 https://github.com/ha-ha-ha-han/UKBiobank_deep_pretrain/tree/master

논문 https://doi.org/10.1016/j.media.2020.101871

Deep Learning Model
VGG 기반 CNN 간소화
Pytorch 라이브러리 활용 설치 코드

# 0. 구글 드라이브 파일 불러오기
"""

from google.colab import drive

drive.mount("/content/drive")

"""# 1. brain_age
- run_20190719_00_epoch_best_mae.p

# 2. sfcn.py
- SFCN 클래스 설정하는 코드
- 40세 ~ 80세까지의 나이 범위(bin)

# 3. dp_loss
- 뇌 나이 예측 SFCN 모델의 손실 함수 중 하나인 KL Divergence(쿨백-라이블러 발산)을 직접 구현한 함수
- 손실 함수란 ? 모델의 출력값과 정답 사이의 "오차(차이)"를 수치로 나타내는 함수

# 4. dp_utils
- 뇌 나이 예측 모델에서 데이터 전처리와 soft label 생성을 위한 유틸리티 함수들을 정의한 파일

# 5. Execution Code
- Soft classification으로 5개 bin 기반 예측 (55–60, ..., 75–80)
- TTA (voxel shifting + mirroring, 3회)
- MC Dropout 예측 (각 TTA당 5회 반복)
- Histogram-aware calibration

## 1) import
"""

import sys
sys.path.append('/content/drive/MyDrive/2025-1학기 Co-Deep/SFCN')


from dp_model.model_files.sfcn import SFCN
from dp_model import dp_loss as dpl
from dp_model import dp_utils as dpu
import torch
import random
import os
import glob
import re
import nibabel as nib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torchvision import models
from collections import Counter
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score


# CPU에서 작동
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# voxel shifting (agumentation)
def voxel_shift(img, max_shift=2):
    """
    img: 3D numpy array or tensor (shape: [D, H, W])
    max_shift: 최대 이동할 voxel 수
    """
    if isinstance(img, torch.Tensor):
        img = img.numpy()

    shift_values = [random.randint(-max_shift, max_shift) for _ in range(3)]
    shifted_img = np.roll(img, shift_values[0], axis=0)  # shift along depth
    shifted_img = np.roll(shifted_img, shift_values[1], axis=1)  # shift height
    shifted_img = np.roll(shifted_img, shift_values[2], axis=2)  # shift width
    return torch.tensor(shifted_img.copy())


# mirroring (augmentation)
def random_mirror(img):
    """
    img: 3D tensor (shape: [D, H, W])
    """
    if random.random() < 0.5:
        # 좌우 뒤집기 (W axis, i.e., last axis)
        img = torch.flip(img, dims=[2])
    return img


def aggregate_probs_to_bins(probs):
    bin_probs = []
    for start, end in bin_ranges:
        indices = [i for i in range(40) if 40+i >= start and 40+i < end]
        bin_prob = probs[indices].sum()
        bin_probs.append(bin_prob)
    bin_probs = np.array(bin_probs)
    bin_probs /= bin_probs.sum()
    return bin_probs

# ── 드라이브 경로 지정 ─────────────────────────
base_dir   = '/content/drive/MyDrive/2025-1학기 Co-Deep/SFCN'
csv_path   = os.path.join(base_dir, 'Participant_LEMON_Mean_Age.csv')
model_path = os.path.join(base_dir, 'brain_age', 'run_20190719_00_epoch_best_mae.p')
input_dir  = os.path.join(base_dir, 'test_older')
output_dir = os.path.join(base_dir, 'results')
# ────────────────────────────────────────────────

# 0. CSV에서 id→age 매핑 읽어오기
age_df   = pd.read_csv(csv_path)
age_map  = dict(zip(age_df['id'], age_df['Mean_age']))

# 1. 모델 초기 설정
model = SFCN()
model = torch.nn.DataParallel(model)
model.load_state_dict(torch.load(model_path, map_location=device))
model.to(device)
model.eval()

# 2. 하이퍼파라미터
bin_ranges = [(55, 60), (60, 65), (65, 70), (70, 75), (75, 80)]
bin_means = np.array([57.5, 62.5, 67.5, 72.5, 77.5])


# 3. input/output 디렉토리 준비
os.makedirs(output_dir, exist_ok=True)
print("Input 디렉토리:", input_dir)
print("Output 디렉토리:", output_dir)

# 4. 결과 저장 리스트
results = []
MC_DROPOUT_RUNS = 5
TTA_RUNS = 3

# 5. NIfTI 파일 찾기
nii_files = glob.glob(os.path.join(input_dir, '*', 'anat', '*.nii*'))
print("Found NIfTI files:", len(nii_files))

"""## 2) 데이터 predicted age & loss 추출"""

# 이미지 하나
for file_path in nii_files:
    print(f"\n▶ Processing: {file_path}")
    filename = os.path.basename(file_path)

    # — CSV에서 subject ID 뽑아서 나이 찾기 —
    m = re.search(r'(sub-\d+)', file_path)
    if not m:
        print("❗ subject ID (sub-XXXXX) 못 찾음")
        continue
    subj = m.group(1)
    age = age_map.get(subj)
    if age is None:
        print(f"❗ CSV에 {subj} 나이가 없음")
        continue
    print(f"Subject: {subj}, True age: {age}")

    try:

        # 6. 이미지 로드 및 전처리
        img = nib.load(file_path)
        data = img.get_fdata()


        # --- (1) 중앙 crop to (160,192,160) ---
        data = data/data.mean()
        data = dpu.crop_center(data, (160, 192, 160))


        # --- (2) Z-score 정규화 ---
        mean = data.mean()
        std = data.std()
        data = (data - mean) / std


        tta_preds = []
        for _ in range(TTA_RUNS):
            # --- (2.5) 데이터 증강 ---
            aug_data = voxel_shift(data, max_shift=3)
            aug_data = random_mirror(aug_data)

            # --- (3) Tensor 변환 및 차원 추가 ---
            input_data = torch.tensor(aug_data, dtype=torch.float32).unsqueeze(0).unsqueeze(0)
            input_data = input_data.to(device)


            # 7. 소프트 라벨 & 예측나이
            mc_preds = []
            model.train()
            with torch.no_grad():
                for _ in range(MC_DROPOUT_RUNS):
                    output = model(input_data)[0].view(-1)
                    probs = torch.exp(output).cpu().numpy()
                    bin_probs = aggregate_probs_to_bins(probs)
                    pred = np.sum(bin_probs * bin_means)
                    mc_preds.append(pred)
            tta_preds.append(np.mean(mc_preds))

        final_pred = np.mean(tta_preds)

        # 8. 예측 & 손실 계산
        with torch.no_grad():
            output = model(input_data)
        x    = output[0].view(1, -1)
        y = torch.tensor(pred, dtype=torch.float32).unsqueeze(0).to(device)
        loss = dpl.my_KLDivLoss(x, y).cpu().item()


        # 10. 결과 기록
        results.append({
            'subject': subj,
            'filename': filename,
            'true_age': age,
            'predicted_age': round(pred, 4),
            'loss': round(loss, 4)
        })


    except Exception as e:
        print(f"❌ Error on {filename}:", e)
        continue

if results:
    df = pd.DataFrame(results)

    out_csv = os.path.join(output_dir, 'brain_age_predictions.csv')
    df.to_csv(out_csv, index=False)
    print(f"\n📁 Saved all results to: {out_csv}")
else:
    print("⚠️ 결과가 하나도 없습니다. 에러 로그를 확인하세요.")

"""## 3) Histogram Aware Calibration"""

if results:
    df = pd.DataFrame(results)

    # Post-hoc bias correction
    print("\n🧠 Applying post-hoc bias correction...")
    y_true = df['true_age'].values.reshape(-1, 1)
    y_pred = df['predicted_age'].values.reshape(-1, 1)

    # 1. 나이대별 가중치 계산 (역비례 가중치)
    # Histogram-Aware Calibration (재샘플링 가중치 적용)
    age_counts = Counter(df['true_age'])
    df['age_weight'] = df['true_age'].map(lambda x: 1.0 / age_counts[x])
    sample_weights = df['age_weight'].values


    # Weighted linear regression
    reg = LinearRegression().fit(y_pred, y_true, sample_weight=sample_weights)
    corrected_pred = reg.predict(y_pred).flatten()
    df['corrected_age'] = np.round(corrected_pred, 4)

    y_pred_final = df['corrected_age'].values.reshape(-1, 1)


    # MAE와 R^2 계산
    mae_before = mean_absolute_error(y_true, y_pred)
    mae_after  = mean_absolute_error(y_true, y_pred_final)
    r2_before  = r2_score(y_true, y_pred)
    r2_after   = r2_score(y_true, y_pred_final)

    print(f"\n📊 MAE Before Correction : {mae_before:.2f}")
    print(f"📊 MAE After Correction  : {mae_after:.2f}")
    print(f"📈 R² Before Correction  : {r2_before:.4f}")
    print(f"📈 R² After Correction   : {r2_after:.4f}")


    summary_row = {
            'subject': 'SUMMARY',
            'filename': '',
            'true_age': '',
            'predicted_age': f'MAE: {mae_before:.2f}, R²: {r2_before:.4f}',
            'loss': '',
            'corrected_age': f'MAE: {mae_after:.2f}, R²: {r2_after:.4f}'
            }
    df = pd.concat([df, pd.DataFrame([summary_row])], ignore_index=True)

    out_csv = os.path.join(output_dir, 'brain_age_predictions.csv')
    df.to_csv(out_csv, index=False)
    print(f"\n📁 Saved all results to: {out_csv}")


else:
  print("⚠️ 결과가 하나도 없습니다. 에러 로그를 확인하세요.")

"""# + 추가 코드 저장소"""