# -*- coding: utf-8 -*-
"""XGBoost_parse_aseg_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1So0d6ExC5a3DwqOylUMvmAxhVQjBJB2x

**aseg.stat-> csv**

이 코드로 피험자별로 순회하면서 아래의 9개만 추출한 csv를 만들어서, 그 다음은 수동으로 기존에 만들어 놓은 feature-name 파일에 복붙한다.

----------------
추출하는 값들 (순서는 CC_Psterior ~ rhCerebralWhiteMatterVol)

참고: CorticalWhiteMatterVol(xgboost)= CerebralWhiteMatterVol(aseg.stat)


**Measure 값(위에 있는 값들) 중에서**

lhCortexVol

rhCortexVol

lhCerebralWhiteMatterVol

rhCerebralWhiteMatterVol

**숫자 데이터 라인(아래에 있는 값들) 중에서**
CC_Posterior

CC_Mid_Posterior

CC_Central

CC_Mid_Anterior

CC_Anterior

# aseg to csv
"""

import os
import csv

# Colab에서 Google Drive 연동
from google.colab import drive
drive.mount('/content/drive')

"""파싱 함수"""

def parse_aseg_stats(filepath):
    """
    FreeSurfer의 aseg.stats 파일에서 필요한 ROI 및 Measure 값만 파싱
    """
    data = {}
    target_rois = {
        "CC_Posterior", "CC_Mid_Posterior", "CC_Central", "CC_Mid_Anterior", "CC_Anterior"
    }
    target_measures = {
        "lhCortexVol", "rhCortexVol", "lhCerebralWhiteMatterVol", "rhCerebralWhiteMatterVol"
    }

    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            # 숫자 데이터 라인
            if not line.startswith("#") and len(line.split()) >= 5:
                parts = line.split()
                try:
                    volume = float(parts[3])
                    struct = parts[4]
                    if struct in target_rois:
                        data[struct] = volume
                except:
                    continue

            # Measure 항목
            elif line.startswith("# Measure"):
                parts = line.split(",")
                if len(parts) >= 4:
                    key = parts[1].strip()
                    try:
                        val = float(parts[3])
                        if key in target_measures:
                            data[key] = val
                    except ValueError:
                        continue
    return data

"""피험자 순회: 베이스 경로 설정"""

base_dir = '/content/drive/MyDrive/2025-1학기 Co-Deep/Data/brain/LEMON/reconall'
output_file = os.path.join(base_dir, "XGBoost_aseg_9.csv")

"""피험자 순회: 순회 코드 및 csv 저장"""

all_rows = []

for subject_id in os.listdir(base_dir):
    if not subject_id.startswith("sub-"):
        continue

    aseg_path = os.path.join(base_dir, subject_id, "stats", "aseg.stats") ## 폴더 구조에 따라 변경 필요!
    if not os.path.isfile(aseg_path):
        print(f"⚠️ {subject_id}: aseg.stats 없음, 건너뜀")
        continue

    try:
        parsed = parse_aseg_stats(aseg_path)
    except Exception as e:
        print(f"❌ {subject_id}: 파싱 실패 - {e}")
        continue

    row = {"ID": subject_id}
    row.update(parsed)
    all_rows.append(row)

# ===== CSV 저장 =====
if all_rows:
    fieldnames = ["ID",
                  "CC_Posterior", "CC_Mid_Posterior", "CC_Central", "CC_Mid_Anterior", "CC_Anterior",
                  "lhCortexVol", "rhCortexVol", "lhCerebralWhiteMatterVol", "rhCerebralWhiteMatterVol"]

    with open(output_file, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in all_rows:
            writer.writerow(row)
    print(f"✅ CSV 저장 완료: {output_file}")
else:
    print("❌ 추출된 데이터 없음")

"""# ROI 이름 순서 일치 확인

HCPMMP 1080개 확인 O

aseg.stat 38개 확인 O
"""

import pandas as pd

orig_file = '/content/drive/MyDrive/2025-1학기 Co-Deep/XGBoost/HCPMMP1.csv_orig6/lh_HCPMMP1_area.csv'
my_file='/content/drive/MyDrive/2025-1학기 Co-Deep/XGBoost/feature-names-1109.xlsx'

# 3. 파일 불러오기
df_A = pd.read_csv(orig_file, sep='\t')
df_B = pd.read_excel(my_file)

# 4. 슬라이싱 (0-index 기준)
cols_A = df_A.columns[2:182]   # 3열 ~ 182열 → 총 180개
cols_B = df_B.columns[723 : 903]   # 4열 ~ 183열 → 총 180개

# 5. 리스트로 변환
list_A = list(cols_A)
list_B = list(cols_B)

# 6. 비교
if list_A == list_B:
    print("✅ 두 파일의 열 이름과 순서가 완전히 일치합니다.")
else:
    print("❌ 열 이름 또는 순서가 일치하지 않습니다.")
    print(f"A 파일 열 개수: {len(list_A)}")
    print(f"B 파일 열 개수: {len(list_B)}")

    # 차이 출력
    for i in range(max(len(list_A), len(list_B))):
        col_a = list_A[i] if i < len(list_A) else "(없음)"
        col_b = list_B[i] if i < len(list_B) else "(없음)"
        if col_a != col_b:
            print(f"열 {i+1}: A = '{col_a}' ≠ B = '{col_b}'")